name: Guiwoo - Test

on:
  push:
    branches: [master]
    paths-ignore:
      - ".github/**"

jobs:
  build:
    name: Build Docker image and push on docker hub
    runs-on: ubuntu-latest

    steps:
      # 소스 가져오기
      - name : Checkout
        uses : actions/checkout@v3
      # Docker build Docker hub push 진행
      - name: Build image and push
        id: build-image
        run: |-
          docker build . -f Dockerfile.dev -t guiwootest
          docker push guiwoo/guiwootest:latest
          
